[package]
name = "pfdirs"
version = "0.1.0"
edition = "2021"

[dependencies]
known-folders = "1.1.0"
winreg = "0.55.0"

[dependencies.windows]
version = "0.62.0"
features = [
    "Win32_System_Com",
    "Win32_UI_Shell",
]
